# Copyright (C) 2026 Dan Michel
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of Windows WNF Registry Bloat Toolkit.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# See the LICENSE file in the project root for the full license text.

<#
.SYNOPSIS
    Collects an unredacted AppX and AppReadiness diagnostic package from
    Windows Server 2019.

.DESCRIPTION
    Collects AppReadiness, AppX deployment, AppModel, shell, Search,
    authentication, StateRepository, User Profile Service, OneDrive updater,
    Application, and System event data when available. It also records
    event-log retention,
    relevant service state, AppX and provisioned-package state, per-profile
    LocalAppData\Packages counts, and AppRepository resiliency-file details.

    CSV summaries are generated by channel, event ID, package, HRESULT, and
    other relevant fields. Raw SIDs and other environment-specific identifiers
    are preserved in this version of the collector.

    This script is read-only. It does not modify services, packages, profiles,
    registry values, event-log settings, or files outside its output directory.

.NOTES
    Run from elevated 64-bit Windows PowerShell 5.1 on Windows Server 2019.

    The output is unredacted and may contain user, server, domain, SID, path,
    tenant, and other environment-specific information. Treat it as sensitive.
#>

[CmdletBinding()]
param(
    [ValidateRange(1, 90)]
    [int] $Days = 7,

    [string] $OutputRoot = (
        Join-Path $env:ProgramData 'WindowsWnfRegistryBloatToolkit'
    )
)

$ErrorActionPreference = 'Stop'
$StartTime = (Get-Date).AddDays(-$Days)
$OperatingSystem = Get-CimInstance Win32_OperatingSystem
$LastBootUpTime = [datetime] $OperatingSystem.LastBootUpTime
$LastBootWithinRequestedWindow = ($LastBootUpTime -ge $StartTime)
$PostBootStartTime = if ($LastBootWithinRequestedWindow) {
    $LastBootUpTime
}
else {
    $StartTime
}
$Timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$OutputDirectory = Join-Path $OutputRoot "AppX-Readiness-Audit-Raw-$Timestamp"

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

function ConvertTo-SafeFileName {
    param([Parameter(Mandatory)][string] $Text)
    return ($Text -replace '[\\/:*?"<>|]', '_')
}

function Get-FirstRegexMatch {
    param(
        [AllowNull()][string] $Text,
        [Parameter(Mandatory)][string] $Pattern
    )

    if ([string]::IsNullOrWhiteSpace($Text)) {
        return $null
    }

    $Match = [regex]::Match(
        $Text,
        $Pattern,
        [Text.RegularExpressions.RegexOptions]::IgnoreCase
    )

    if ($Match.Success) {
        return $Match.Value
    }

    return $null
}

function Get-AllRegexMatches {
    param(
        [AllowNull()][string] $Text,
        [Parameter(Mandatory)][string] $Pattern
    )

    if ([string]::IsNullOrWhiteSpace($Text)) {
        return ''
    }

    return (
        [regex]::Matches(
            $Text,
            $Pattern,
            [Text.RegularExpressions.RegexOptions]::IgnoreCase
        ) |
        ForEach-Object { $_.Value.ToUpperInvariant() } |
        Sort-Object -Unique
    ) -join ';'
}

function Get-EventErrorCodes {
    param(
        [AllowNull()][string] $Text
    )

    if ([string]::IsNullOrWhiteSpace($Text)) {
        return ''
    }

    $Codes = New-Object 'System.Collections.Generic.List[string]'

    foreach (
        $Match in [regex]::Matches(
            $Text,
            '\b0x[0-9A-Fa-f]{8}\b',
            [Text.RegularExpressions.RegexOptions]::IgnoreCase
        )
    ) {
        [void] $Codes.Add($Match.Value.ToUpperInvariant())
    }

    foreach (
        $Match in [regex]::Matches(
            $Text,
            '\b(?:hr|hresult)\s*[:=]?\s*(?<Code>[0-9A-Fa-f]{8})\b',
            [Text.RegularExpressions.RegexOptions]::IgnoreCase
        )
    ) {
        [void] $Codes.Add(
            ('0X{0}' -f $Match.Groups['Code'].Value.ToUpperInvariant())
        )
    }

    return (
        $Codes |
        Sort-Object -Unique
    ) -join ';'
}

function Convert-EventRecord {
    param(
        [Parameter(Mandatory)]
        [System.Diagnostics.Eventing.Reader.EventRecord] $Event
    )

    $Message = $null
    try {
        $Message = $Event.Message
    }
    catch {
        $Message = '<Message rendering failed>'
    }

    $ActivityId = $null
    $RelatedActivityId = $null
    $ProcessId = $null
    $ThreadId = $null
    $SystemUserId = $null

    try {
        $Xml = [xml] $Event.ToXml()

        $Correlation = $Xml.Event.System.Correlation
        if ($null -ne $Correlation) {
            $ActivityId = [string] $Correlation.ActivityID
            $RelatedActivityId = [string] $Correlation.RelatedActivityID
        }

        $Execution = $Xml.Event.System.Execution
        if ($null -ne $Execution) {
            $ProcessId = [string] $Execution.ProcessID
            $ThreadId = [string] $Execution.ThreadID
        }

        $Security = $Xml.Event.System.Security
        if ($null -ne $Security) {
            $SystemUserId = [string] $Security.UserID
        }
    }
    catch {
    }

    $PackageName = Get-FirstRegexMatch `
        -Text $Message `
        -Pattern '\bMicrosoft\.[A-Za-z0-9.-]+(?:_[A-Za-z0-9.\-]+)*\b'

    $ErrorCodes = Get-EventErrorCodes -Text $Message

    $UserSids = Get-AllRegexMatches `
        -Text $Message `
        -Pattern '\bS-\d-\d+(?:-\d+){1,}\b'

    [pscustomobject]@{
        TimeCreated        = $Event.TimeCreated
        RecordId          = $Event.RecordId
        LogName           = $Event.LogName
        ProviderName      = $Event.ProviderName
        EventId           = $Event.Id
        Level             = $Event.LevelDisplayName
        TaskDisplayName   = $Event.TaskDisplayName
        OpcodeDisplayName = $Event.OpcodeDisplayName
        ActivityId        = $ActivityId
        RelatedActivityId = $RelatedActivityId
        ProcessId         = $ProcessId
        ThreadId          = $ThreadId
        SystemUserSid     = $SystemUserId
        MessageUserSids   = $UserSids
        PackageName       = $PackageName
        ErrorCodes        = $ErrorCodes
        MachineName       = $Event.MachineName
        Message           = $Message
    }
}

function Export-EventChannel {
    param(
        [Parameter(Mandatory)][string] $LogName,
        [Parameter(Mandatory)][datetime] $FromTime,
        [Parameter(Mandatory)][string] $DestinationDirectory
    )

    $LogInfo = Get-WinEvent -ListLog $LogName -ErrorAction SilentlyContinue

    if ($null -eq $LogInfo) {
        return [pscustomobject]@{
            LogName       = $LogName
            Exists        = $false
            Enabled       = $false
            RecordCount   = $null
            ExportedCount = 0
            CsvPath       = ''
            Error         = 'Channel not present'
        }
    }

    $Events = @()

    try {
        $Events = @(
            Get-WinEvent -FilterHashtable @{
                LogName   = $LogName
                StartTime = $FromTime
            } -ErrorAction Stop
        )
    }
    catch {
        if (
            $_.Exception.Message -notmatch
                'No events were found that match the specified selection criteria'
        ) {
            return [pscustomobject]@{
                LogName       = $LogName
                Exists        = $true
                Enabled       = $LogInfo.IsEnabled
                RecordCount   = $LogInfo.RecordCount
                ExportedCount = 0
                CsvPath       = ''
                Error         = $_.Exception.Message
            }
        }
    }

    $Rows = @(
        foreach ($Event in $Events) {
            Convert-EventRecord -Event $Event
        }
    )

    $SafeName = ConvertTo-SafeFileName -Text $LogName
    $CsvPath = Join-Path $DestinationDirectory "$SafeName.csv"

    $Rows |
        Export-Csv -LiteralPath $CsvPath -NoTypeInformation -Encoding UTF8

    foreach ($Row in $Rows) {
        [void] $script:AllEventRows.Add($Row)
    }

    return [pscustomobject]@{
        LogName       = $LogName
        Exists        = $true
        Enabled       = $LogInfo.IsEnabled
        RecordCount   = $LogInfo.RecordCount
        ExportedCount = $Rows.Count
        CsvPath       = $CsvPath
        Error         = ''
    }
}

function Get-OldestNewestEvent {
    param([Parameter(Mandatory)][string] $LogName)

    $Oldest = $null
    $Newest = $null

    try {
        $Oldest = Get-WinEvent -LogName $LogName -Oldest -MaxEvents 1 -ErrorAction Stop
    }
    catch {
    }

    try {
        $Newest = Get-WinEvent -LogName $LogName -MaxEvents 1 -ErrorAction Stop
    }
    catch {
    }

    [pscustomobject]@{
        OldestRetained = if ($null -ne $Oldest) { $Oldest.TimeCreated } else { $null }
        NewestRetained = if ($null -ne $Newest) { $Newest.TimeCreated } else { $null }
    }
}

$TargetLogs = @(
    'Microsoft-Windows-AppReadiness/Admin'
    'Microsoft-Windows-AppReadiness/Operational'
    'Microsoft-Windows-AppXDeployment/Operational'
    'Microsoft-Windows-AppXDeploymentServer/Operational'
    'Microsoft-Windows-AppModel-Runtime/Admin'
    'Microsoft-Windows-AppModel-State/Admin'
    'Microsoft-Windows-TWinUI/Operational'
    'Microsoft-Windows-Shell-Core/Operational'
    'Microsoft-Windows-Search/Operational'
    'Microsoft-Windows-StateRepository/Operational'
    'Microsoft-Windows-AAD/Operational'
    'Microsoft-Windows-WebAuth/Operational'
    'Microsoft-Windows-CloudExperienceHost/Operational'
    'Microsoft-Windows-User Profile Service/Operational'
)

$script:AllEventRows = New-Object 'System.Collections.Generic.List[object]'
$ChannelResults = New-Object 'System.Collections.Generic.List[object]'

foreach ($LogName in $TargetLogs) {
    Write-Host "Collecting: $LogName"

    $Result = Export-EventChannel `
        -LogName $LogName `
        -FromTime $StartTime `
        -DestinationDirectory $OutputDirectory

    [void] $ChannelResults.Add($Result)
}

$RelevantPattern =
    'AppReadiness|' +
    'AppX|' +
    'AppContainer|' +
    'Cortana|' +
    'SearchUI|' +
    'SearchIndexer|' +
    'ShellExperienceHost|' +
    'StartMenuExperienceHost|' +
    'AAD\.BrokerPlugin|' +
    'TokenBroker|' +
    'RuntimeBroker|' +
    'backgroundTaskHost|' +
    'BrokerInfrastructure|' +
    'SystemEventsBroker|' +
    'StateRepository|' +
    'OneDriveUpdaterService|' +
    'OneDrive(?:\.exe)?'

foreach ($StandardLog in @('Application', 'System')) {
    Write-Host "Collecting relevant events from: $StandardLog"

    $MatchingEvents = @()

    try {
        $MatchingEvents = @(
            Get-WinEvent -FilterHashtable @{
                LogName   = $StandardLog
                StartTime = $StartTime
            } -ErrorAction Stop |
            Where-Object {
                $_.ProviderName -match $RelevantPattern -or
                $_.Message -match $RelevantPattern
            }
        )
    }
    catch {
        if (
            $_.Exception.Message -notmatch
                'No events were found that match the specified selection criteria'
        ) {
            Write-Warning "Could not fully query $StandardLog`: $($_.Exception.Message)"
        }
    }

    $Rows = @(
        foreach ($Event in $MatchingEvents) {
            Convert-EventRecord -Event $Event
        }
    )

    $CsvPath = Join-Path $OutputDirectory "$StandardLog-Relevant.csv"

    $Rows |
        Export-Csv -LiteralPath $CsvPath -NoTypeInformation -Encoding UTF8

    foreach ($Row in $Rows) {
        [void] $script:AllEventRows.Add($Row)
    }

    [void] $ChannelResults.Add(
        [pscustomobject]@{
            LogName       = "$StandardLog (filtered)"
            Exists        = $true
            Enabled       = $true
            RecordCount   = $null
            ExportedCount = $Rows.Count
            CsvPath       = $CsvPath
            Error         = ''
        }
    )
}

# Windows PowerShell 5.1 can throw "Argument types do not match" when
# the array-subexpression operator is used directly against a generic List[object].
# ToArray() performs the conversion without invoking that binder path.
$AllEvents = $script:AllEventRows.ToArray()

$AllEvents |
    Sort-Object TimeCreated |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'All-Relevant-Events.csv'
    ) -NoTypeInformation -Encoding UTF8

$AllEvents |
    Group-Object LogName, ProviderName, EventId, Level |
    ForEach-Object {
        $Example = $_.Group | Select-Object -First 1
        $Ordered = $_.Group | Sort-Object TimeCreated

        [pscustomobject]@{
            LogName       = $Example.LogName
            ProviderName  = $Example.ProviderName
            EventId       = $Example.EventId
            Level         = $Example.Level
            Count         = $_.Count
            FirstObserved = $Ordered[0].TimeCreated
            LastObserved  = $Ordered[-1].TimeCreated
        }
    } |
    Sort-Object Count -Descending |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Summary-ByLog-EventId.csv'
    ) -NoTypeInformation -Encoding UTF8

$ErrorCodeRows = foreach ($Event in $AllEvents) {
    if ([string]::IsNullOrWhiteSpace($Event.ErrorCodes)) {
        continue
    }

    foreach ($Code in $Event.ErrorCodes -split ';') {
        [pscustomobject]@{
            ErrorCode    = $Code
            LogName      = $Event.LogName
            ProviderName = $Event.ProviderName
            EventId      = $Event.EventId
            PackageName = $Event.PackageName
            TimeCreated = $Event.TimeCreated
        }
    }
}

$ErrorCodeRows |
    Group-Object ErrorCode, LogName, ProviderName, EventId |
    ForEach-Object {
        $Example = $_.Group | Select-Object -First 1
        $Ordered = $_.Group | Sort-Object TimeCreated

        [pscustomobject]@{
            ErrorCode     = $Example.ErrorCode
            LogName       = $Example.LogName
            ProviderName  = $Example.ProviderName
            EventId       = $Example.EventId
            Count         = $_.Count
            FirstObserved = $Ordered[0].TimeCreated
            LastObserved  = $Ordered[-1].TimeCreated
        }
    } |
    Sort-Object Count -Descending |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Summary-ByErrorCode.csv'
    ) -NoTypeInformation -Encoding UTF8

$AllEvents |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_.PackageName) } |
    Group-Object PackageName, EventId, ErrorCodes |
    ForEach-Object {
        $Example = $_.Group | Select-Object -First 1
        $Ordered = $_.Group | Sort-Object TimeCreated

        [pscustomobject]@{
            PackageName   = $Example.PackageName
            EventId       = $Example.EventId
            ErrorCodes    = $Example.ErrorCodes
            Count         = $_.Count
            FirstObserved = $Ordered[0].TimeCreated
            LastObserved  = $Ordered[-1].TimeCreated
        }
    } |
    Sort-Object Count -Descending |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Summary-ByPackage.csv'
    ) -NoTypeInformation -Encoding UTF8

# Keep the original requested-window summaries above, and also emit a second
# view bounded by the most recent boot. When the boot predates the requested
# collection window, the post-boot view is necessarily truncated to StartTime.
$PostBootEvents = @(
    $AllEvents |
        Where-Object { $_.TimeCreated -ge $PostBootStartTime }
)

$PostBootEvents |
    Sort-Object TimeCreated |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'PostBoot-Relevant-Events.csv'
    ) -NoTypeInformation -Encoding UTF8

$PostBootEvents |
    Group-Object LogName, ProviderName, EventId, Level |
    ForEach-Object {
        $Example = $_.Group | Select-Object -First 1
        $Ordered = $_.Group | Sort-Object TimeCreated

        [pscustomobject]@{
            LogName       = $Example.LogName
            ProviderName  = $Example.ProviderName
            EventId       = $Example.EventId
            Level         = $Example.Level
            Count         = $_.Count
            FirstObserved = $Ordered[0].TimeCreated
            LastObserved  = $Ordered[-1].TimeCreated
        }
    } |
    Sort-Object Count -Descending |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Summary-PostBoot-ByLog-EventId.csv'
    ) -NoTypeInformation -Encoding UTF8

$PostBootErrorCodeRows = foreach ($Event in $PostBootEvents) {
    if ([string]::IsNullOrWhiteSpace($Event.ErrorCodes)) {
        continue
    }

    foreach ($Code in $Event.ErrorCodes -split ';') {
        [pscustomobject]@{
            ErrorCode    = $Code
            LogName      = $Event.LogName
            ProviderName = $Event.ProviderName
            EventId      = $Event.EventId
            PackageName  = $Event.PackageName
            TimeCreated  = $Event.TimeCreated
        }
    }
}

$PostBootErrorCodeRows |
    Group-Object ErrorCode, LogName, ProviderName, EventId |
    ForEach-Object {
        $Example = $_.Group | Select-Object -First 1
        $Ordered = $_.Group | Sort-Object TimeCreated

        [pscustomobject]@{
            ErrorCode     = $Example.ErrorCode
            LogName       = $Example.LogName
            ProviderName  = $Example.ProviderName
            EventId       = $Example.EventId
            Count         = $_.Count
            FirstObserved = $Ordered[0].TimeCreated
            LastObserved  = $Ordered[-1].TimeCreated
        }
    } |
    Sort-Object Count -Descending |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Summary-PostBoot-ByErrorCode.csv'
    ) -NoTypeInformation -Encoding UTF8

$PostBootEvents |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_.PackageName) } |
    Group-Object PackageName, EventId, ErrorCodes |
    ForEach-Object {
        $Example = $_.Group | Select-Object -First 1
        $Ordered = $_.Group | Sort-Object TimeCreated

        [pscustomobject]@{
            PackageName   = $Example.PackageName
            EventId       = $Example.EventId
            ErrorCodes    = $Example.ErrorCodes
            Count         = $_.Count
            FirstObserved = $Ordered[0].TimeCreated
            LastObserved  = $Ordered[-1].TimeCreated
        }
    } |
    Sort-Object Count -Descending |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Summary-PostBoot-ByPackage.csv'
    ) -NoTypeInformation -Encoding UTF8

@(
    [pscustomobject]@{
        Scope            = 'RequestedWindow'
        WindowStart      = $StartTime
        WindowEnd        = Get-Date
        EventCount       = $AllEvents.Count
        BoundaryComplete = $true
        Note             = 'Full requested collection window.'
    }
    [pscustomobject]@{
        Scope            = 'PostBoot'
        WindowStart      = $PostBootStartTime
        WindowEnd        = Get-Date
        EventCount       = $PostBootEvents.Count
        BoundaryComplete = $LastBootWithinRequestedWindow
        Note             = if ($LastBootWithinRequestedWindow) {
            'Complete from the most recent boot.'
        }
        else {
            'Most recent boot predates StartTime; post-boot view is truncated to the requested collection window.'
        }
    }
) |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Event-Window-Summary.csv'
    ) -NoTypeInformation -Encoding UTF8

$LogRetentionRows = foreach ($LogName in $TargetLogs) {
    $Info = Get-WinEvent -ListLog $LogName -ErrorAction SilentlyContinue

    if ($null -eq $Info) {
        [pscustomobject]@{
            LogName        = $LogName
            Present        = $false
            Enabled        = $false
            RecordCount    = $null
            MaximumSizeMB  = $null
            LogMode        = ''
            OldestRetained = $null
            NewestRetained = $null
        }
        continue
    }

    $Range = Get-OldestNewestEvent -LogName $LogName

    [pscustomobject]@{
        LogName        = $LogName
        Present        = $true
        Enabled        = $Info.IsEnabled
        RecordCount    = $Info.RecordCount
        MaximumSizeMB  = [Math]::Round($Info.MaximumSizeInBytes / 1MB, 2)
        LogMode        = $Info.LogMode
        OldestRetained = $Range.OldestRetained
        NewestRetained = $Range.NewestRetained
    }
}

$LogRetentionRows |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'EventLog-Retention.csv'
    ) -NoTypeInformation -Encoding UTF8

$ChannelResults |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'EventLog-CollectionStatus.csv'
    ) -NoTypeInformation -Encoding UTF8

$RelevantServiceNames = @(
    'AppReadiness'
    'AppXSvc'
    'StateRepository'
    'TokenBroker'
    'BrokerInfrastructure'
    'SystemEventsBroker'
    'WSearch'
    'ClipSVC'
    'UserManager'
    'ProfSvc'
    'OneDriveUpdaterService'
)

$ServiceRows = foreach ($ServiceName in $RelevantServiceNames) {
    $Service = Get-CimInstance `
        -ClassName Win32_Service `
        -Filter "Name='$ServiceName'" `
        -ErrorAction SilentlyContinue

    if ($null -eq $Service) {
        [pscustomobject]@{
            Name        = $ServiceName
            Present     = $false
            DisplayName = ''
            State       = ''
            StartMode   = ''
            StartName   = ''
            ProcessId   = ''
            PathName    = ''
        }
        continue
    }

    [pscustomobject]@{
        Name        = $Service.Name
        Present     = $true
        DisplayName = $Service.DisplayName
        State       = $Service.State
        StartMode   = $Service.StartMode
        StartName   = $Service.StartName
        ProcessId   = $Service.ProcessId
        PathName    = $Service.PathName
    }
}

$ServiceRows |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Relevant-Services.csv'
    ) -NoTypeInformation -Encoding UTF8

$RelevantPackagePattern =
    'Cortana|' +
    'AAD\.BrokerPlugin|' +
    'ShellExperienceHost|' +
    'StartMenuExperienceHost|' +
    'CloudExperienceHost|' +
    'AccountsControl|' +
    'SecHealthUI'

$PackageRows = @()

try {
    $PackageRows = @(
        Get-AppxPackage -AllUsers -ErrorAction Stop |
        Where-Object { $_.Name -match $RelevantPackagePattern } |
        ForEach-Object {
            [pscustomobject]@{
                Name                   = $_.Name
                PackageFullName        = $_.PackageFullName
                PackageFamilyName      = $_.PackageFamilyName
                Version                = $_.Version
                Architecture           = $_.Architecture
                Publisher              = $_.Publisher
                InstallLocation        = $_.InstallLocation
                Status                 = $_.Status
                IsFramework            = $_.IsFramework
                NonRemovable           = $_.NonRemovable
                PackageUserInformation = (
                    $_.PackageUserInformation |
                    ForEach-Object { [string] $_ }
                ) -join '; '
            }
        }
    )
}
catch {
    Write-Warning "Get-AppxPackage -AllUsers failed: $($_.Exception.Message)"
}

$PackageRows |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Relevant-AppxPackages-AllUsers.csv'
    ) -NoTypeInformation -Encoding UTF8

$ProvisionedRows = @()

try {
    $ProvisionedRows = @(
        Get-AppxProvisionedPackage -Online -ErrorAction Stop |
        Where-Object {
            $_.DisplayName -match $RelevantPackagePattern -or
            $_.PackageName -match $RelevantPackagePattern
        } |
        Select-Object DisplayName, Version, Architecture, ResourceId, PackageName, Regions
    )
}
catch {
    Write-Warning "Get-AppxProvisionedPackage failed: $($_.Exception.Message)"
}

$ProvisionedRows |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Relevant-ProvisionedPackages.csv'
    ) -NoTypeInformation -Encoding UTF8

$ProfileRows = foreach (
    $Profile in Get-CimInstance Win32_UserProfile |
        Where-Object {
            -not $_.Special -and
            -not [string]::IsNullOrWhiteSpace($_.LocalPath)
        }
) {
    $PackagesPath = Join-Path $Profile.LocalPath 'AppData\Local\Packages'
    $PackageDirectories = @()

    if (Test-Path -LiteralPath $PackagesPath) {
        try {
            $PackageDirectories = @(
                Get-ChildItem `
                    -LiteralPath $PackagesPath `
                    -Directory `
                    -Force `
                    -ErrorAction Stop
            )
        }
        catch {
            $PackageDirectories = @()
        }
    }

    [pscustomobject]@{
        Sid                    = $Profile.SID
        LocalPath              = $Profile.LocalPath
        Loaded                 = $Profile.Loaded
        LastUseTime            = $Profile.LastUseTime
        PackagesFolderExists   = Test-Path -LiteralPath $PackagesPath
        PackageDirectoryCount  = $PackageDirectories.Count
        CortanaFolderPresent   = [bool](
            $PackageDirectories.Name -match '^Microsoft\.Windows\.Cortana_'
        )
        AADBrokerFolderPresent = [bool](
            $PackageDirectories.Name -match '^Microsoft\.AAD\.BrokerPlugin_'
        )
        ShellFolderPresent     = [bool](
            $PackageDirectories.Name -match 'ShellExperienceHost'
        )
    }
}

$ProfileRows |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'Profile-Packages-Inventory.csv'
    ) -NoTypeInformation -Encoding UTF8

$AppRepositoryPath = Join-Path $env:ProgramData 'Microsoft\Windows\AppRepository'
    $ResiliencyRows = @()

if (Test-Path -LiteralPath $AppRepositoryPath) {
    $ResiliencyRows = @(
        Get-ChildItem `
            -LiteralPath $AppRepositoryPath `
            -Filter '*.rslc' `
            -File `
            -Force `
            -ErrorAction SilentlyContinue |
        ForEach-Object {
            $Sid = Get-FirstRegexMatch `
                -Text $_.Name `
                -Pattern 'S-\d-\d+(?:-\d+){1,}'

            [pscustomobject]@{
                Name          = $_.Name
                FullName      = $_.FullName
                Length        = $_.Length
                CreationTime  = $_.CreationTime
                LastWriteTime = $_.LastWriteTime
                UserSid       = $Sid
            }
        }
    )
}

$ResiliencyRows |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'AppRepository-ResiliencyFiles.csv'
    ) -NoTypeInformation -Encoding UTF8

$ResiliencyRows |
    Group-Object UserSid |
    ForEach-Object {
        $Ordered = $_.Group | Sort-Object CreationTime

        [pscustomobject]@{
            UserSid    = $_.Name
            FileCount  = $_.Count
            TotalBytes = ($_.Group | Measure-Object Length -Sum).Sum
            OldestFile = $Ordered[0].CreationTime
            NewestFile = $Ordered[-1].CreationTime
        }
    } |
    Sort-Object FileCount -Descending |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'AppRepository-ResiliencySummary.csv'
    ) -NoTypeInformation -Encoding UTF8

$ComputerSystem = Get-CimInstance Win32_ComputerSystem

$SystemSummary = [pscustomobject]@{
    CollectedAt         = Get-Date
    ComputerName        = $env:COMPUTERNAME
    StartTime           = $StartTime
    DaysRequested       = $Days
    Caption             = $OperatingSystem.Caption
    Version             = $OperatingSystem.Version
    BuildNumber         = $OperatingSystem.BuildNumber
    LastBootUpTime      = $LastBootUpTime
    LastBootWithinRequestedWindow = $LastBootWithinRequestedWindow
    PostBootWindowStart  = $PostBootStartTime
    PostBootEventsExported = $PostBootEvents.Count
    UptimeDays          = [Math]::Round(
        ((Get-Date) - $OperatingSystem.LastBootUpTime).TotalDays,
        2
    )
    TotalPhysicalGB     = [Math]::Round(
        $ComputerSystem.TotalPhysicalMemory / 1GB,
        2
    )
    TotalEventsExported = $AllEvents.Count
    ResiliencyFileCount = $ResiliencyRows.Count
    OutputDirectory     = $OutputDirectory
}

$SystemSummary |
    Export-Csv -LiteralPath (
        Join-Path $OutputDirectory 'System-Summary.csv'
    ) -NoTypeInformation -Encoding UTF8

Write-Host
Write-Host 'Read-only AppX/AppReadiness audit completed.'
Write-Host "Events exported: $($AllEvents.Count)"
Write-Host "Output folder:   $OutputDirectory"
